pipeline {
    agent any

    environment {
        // Define your Maven home if needed
        MAVEN_HOME = tool 'mvn-3.9.5' // Ensure Maven is configured in Jenkins Global Tool Configuration
    }

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    // Checkout the code from the Git repository
                    git branch: 'main',
                        credentialsId: 'github_krishnarcm',
                        url: 'https://github.com/krishnar-cm/sample-spring-microservices-new.git'
                }
            }
        }

        stage('Build with Maven') {
            steps {
                script {
                  dir('config-service') {
                    // Run Maven build
                    sh "'${MAVEN_HOME}/bin/mvn' clean install" // Adjust the command as necessary for your build
                  }
                }
            }
        }
    }

    post {
        success {
            echo 'Build completed successfully!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
